---
ID: "fe22b281-3e9a-46f3-9ccb-b0d82fdd23ce"
Parent: "73c59589-2bc6-4200-a631-7bac9d33ae64"
Template: "94a8c8e9-690b-4e65-98e7-f95800222767"
Path: /sitecore/content/Habitat/NewHome/Services/Product Warranty Information
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{3CDF4DD8-28A4-4185-8C09-A73CAA4633F7}"
          s:ds="{574E1DCF-4AA6-444B-B856-1820BA7513E5}"
          s:par="" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: Product Warranty Information
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170316T132158Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "9492e0bb-9df9-46e7-8188-ec795c4ade44"
      Hint: Image
      Value: |
        <image mediaid="{BCB50FB9-9947-4D2A-843D-EBB66D25CFF1}" />
    - ID: "ac3fd4db-8266-476d-9635-67814d91e901"
      Hint: Summary
      Value: Product warranties for peace of mind.
    - ID: "c30a013f-3cc8-4961-9837-1c483277084a"
      Hint: Title
      Value: Product Warranty Information
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: "Services - SmartLife"
    - ID: "d74f396d-5c5e-4916-bd0a-bfd58b6b1967"
      Hint: Body
      Value: |
        <h1 style="background: white; margin: 0cm 0cm 9pt;"><span style="color: #333333;">SmartLife Warranty &amp; extended warranties</span></h1>
        <h2 style="background: white; margin: 0cm 0cm 7.5pt;"><strong><span style="color: #333333;">What warranty comes with a SmartLife appliance?</span></strong></h2>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">The SmartLife warranty on your appliance depends on whether you bought it from one of the USA dealers or online. All SmartLife appliances come with a standard one year guarantee but:</span></p>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">If you bought it online from SmartLife USA, you will have an additional five years parts-only guarantee.</span></p>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">For a better after sales service, you can choose to register your appliance<span class="apple-converted-space">&nbsp;</span>with SmartLife.</span></p>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">If you need to book a repair, call customer services on&nbsp;+<strong>1844 481 0250.</strong></span></p>
        <h3 style="background: white; margin: 0cm 0cm 7.5pt;"><strong><span style="color: #333333;">My SmartLife appliance is out of warranty</span></strong></h3>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">The warranty on your appliance provides you with that initial peace of mind that if something unexpected happens to your appliance, you won&rsquo;t have to spend the money to get your business running smoothly again because it will sorted out by a qualified appliance technician. When your appliance is out of warranty, you no longer have that peace of mind and this is where our extended warranties are essential.</span></p>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">Smartlife.com commercial appliance insurance covers parts, labour and call-out charges.</span></p>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">Whether you have a SmartLife appliance, we offer an extended warranty for many appliances, even those more than 8 years old (provided they have no pre-existing faults and are less than 8 years old at the start of the policy) &ndash; choose either single cover or one policy to cover many appliances in your home.</span></p>
        <h3 style="background: white; margin: 0cm 0cm 7.5pt;"><strong><span style="color: #333333;">Making a claim under SmartLife extended warranty</span></strong></h3>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">Making a claim and requesting a call out is quick and easy with us. All you need to do is call us on&nbsp;+1844 481 0250&nbsp;(Monday to Friday 9am &ndash; 5pm) with details on the breakdown. Once your claim is approved, we will call you to arrange a time to fix your appliance that is convenient.</span></p>
        <h3 style="background: white; margin: 0cm 0cm 7.5pt;"><strong><span style="color: #333333;">About SmartLife</span></strong></h3>
        <p style="background: white; margin: 0cm 0cm 7.5pt;"><span style="color: #333333;">As one of the largest appliance manufacturers in the world and with over a 30 year&rsquo;s experience under their belt, SmartLife is a company that offers innovative and top quality designs and a brand that lasts.</span></p>
