---
ID: "73c59589-2bc6-4200-a631-7bac9d33ae64"
Parent: "0a165175-80f7-4d74-abfe-1e8371df0761"
Template: "dea33c28-4ea0-48e9-a226-0b409411aba8"
Path: /sitecore/content/Habitat/NewHome/Services
DB: master
SharedFields:
- ID: "5585a30d-b115-4753-93ce-422c3455deb2"
  Hint: ShowInNavigation
  Type: Checkbox
  Value: 1
- ID: "68016087-aa00-45d6-922a-678475c50d4a"
  Hint: ShowChildren
  Type: Checkbox
  Value: 0
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 275
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: Services
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170314T114200Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "9492e0bb-9df9-46e7-8188-ec795c4ade44"
      Hint: Image
      Value: |
        <image mediaid="{7C358D66-E47C-4C44-A4D1-2125E531F801}" />
    - ID: "ac3fd4db-8266-476d-9635-67814d91e901"
      Hint: Summary
      Value: Service you can depend on.Fast, competent, always ready to listen to your wishes and concerns. SmartLife Customer Service ensures that you can start using your SmartLife commercial appliances again quickly, whether it's a washing machine or air conditioner or a refrigerator
    - ID: "c30a013f-3cc8-4961-9837-1c483277084a"
      Hint: Title
      Value: Services
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: "Services - SmartLife"
    - ID: "d74f396d-5c5e-4916-bd0a-bfd58b6b1967"
      Hint: Body
      Value: "<p>At SmartLife, we create innovative, stylish, state-of-the-art products and back them up with&nbsp;SmartLife Customer Service and Support designed to make life good. Whether you need owner manuals, parts and accessories, mobile phone support, or warranty information, you will find&nbsp;SmartLife Technical Support and everything else you need ? Just a few clicks away. If you want to speak with someone, SmartLife Support has courteous, respectful and knowledgeable individuals that can assist you with all technical support and service issues. </p>"
